export const MIN_OBJECTS_COUNT = 2;
export const MAX_OBJECTS_COUNT = 7;
export const MIN_PARAMETERS_COUNT = 1;
export const MAX_PARAMETERS_COUNT = 7;

export const COMPARISON_VALUES = {
    ABSOLUTELY_INFERIOR: 1/9,
    CLEARLY_LESS_PREFERABLE: 1/7,
    MUCH_LESS_PREFERABLE: 1/5,
    SLIGHTLY_LESS_PREFERABLE: 1/3,
    SAME_DEGREE_OF_PREFERENCE: 1.0,
    SLIGHTLY_PREFERABLE: 3.0,
    MUCH_PREFERABLE: 5.0,
    CLEARLY_PREFERABLE: 7.0,
    ABSOLUTELY_SUPERIOR: 9.0,
};

export const SHORT_COMPARISON_PRECISION = 2;

export const SHORT_COMPARISON_VALUES_TO_LONG = Object.keys(COMPARISON_VALUES).reduce((map, comparison) => {
    const comparisonValue = COMPARISON_VALUES[comparison];

    map[comparisonValue.toFixed(SHORT_COMPARISON_PRECISION)] = comparisonValue;

    return map;
}, {});


export const COMPARISON_VALUES_TO_STRING = {
    [COMPARISON_VALUES.ABSOLUTELY_INFERIOR]: '1/9',
    [COMPARISON_VALUES.CLEARLY_LESS_PREFERABLE]: '1/7',
    [COMPARISON_VALUES.MUCH_LESS_PREFERABLE]: '1/5',
    [COMPARISON_VALUES.SLIGHTLY_LESS_PREFERABLE]: '1/3',
    [COMPARISON_VALUES.SAME_DEGREE_OF_PREFERENCE]: '1',
    [COMPARISON_VALUES.SLIGHTLY_PREFERABLE]: '3',
    [COMPARISON_VALUES.MUCH_PREFERABLE]: '5',
    [COMPARISON_VALUES.CLEARLY_PREFERABLE]: '7',
    [COMPARISON_VALUES.ABSOLUTELY_SUPERIOR]: '9',
};

export const COMPARISON_LABELS = {
    [COMPARISON_VALUES.ABSOLUTELY_INFERIOR]: 'is absolutely inferior to',
    [COMPARISON_VALUES.CLEARLY_LESS_PREFERABLE]: 'is clearly less preferable to',
    [COMPARISON_VALUES.MUCH_LESS_PREFERABLE]: 'is much less preferable to',
    [COMPARISON_VALUES.SLIGHTLY_LESS_PREFERABLE]: 'is slightly less preferable to',
    [COMPARISON_VALUES.SAME_DEGREE_OF_PREFERENCE]: 'has the same degree of preference as',
    [COMPARISON_VALUES.SLIGHTLY_PREFERABLE]: 'is slightly preferable to',
    [COMPARISON_VALUES.MUCH_PREFERABLE]: 'is much preferable to',
    [COMPARISON_VALUES.CLEARLY_PREFERABLE]: 'is clearly preferable to',
    [COMPARISON_VALUES.ABSOLUTELY_SUPERIOR]: 'is absolutely superior to',
};

export const WIDGET_TYPE = {
    LIST: 'LIST',
    MATRIX: 'MATRIX',
};
